### ISSUE TITLE
Node2Vec in a large graph

### ISSUE THREAD

**Issue by timilsinamohan** [VHRanger/nodevectors#28] opened 2020-12-22 15:59 UTC
Hi,
Thanks for the clarification to solve the [Issue number 27](https://github.com/VHRanger/nodevectors/issues/27). Now that works fine after I upgrade the `csrgraph `to version `0.1.27`.  Now the next issue is that I got  `Segmentation fault` while running node2vec.  Is there any suggestion to fix this? 

```
G = csr_matrix(G)
n2v_model = nodevectors.Node2Vec()
n2v_model.fit(G)
```
`Segmentation fault`

Do I need to update the nodevectors package as well after I update the `csrgraph ` ? If so which version is needed?

Thanks in advance !

**Comment by VHRanger** [comment] 2020-12-22 18:58
If you absolutely insist on running Node2Vec, I'd recommend modifying the settings in the `Node2Vec` class like this

```python
 nodevectors.Node2Vec(
        walklen=20, 
        epochs=5,
        return_weight=1.,
        neighbor_weight=1.,
        threads=1, 
        verbose=True
)
```

Segfaults are generally related to threading (so `threads >= 2` or `threads = 0`) with using return_weight or neighbor_weight different than 1.

You can always try some of the other embedding algorithms (GGVec, GraRep, ProNE) -- Node2Vec is the only one that has this segfault issue and it's been hard to replicate and find the cause as of yet. Node2Vec is also not particularly better than the other ones, it's just more well known.

To help with the segfault, can you send me your setup? Your computer, python, numpy, numba version the Node2Vec settings used and either a link to your graph data or some statistics on it (directed or undirected, number of nodes and edges, etc.)

Thanks

**Comment by VHRanger** [comment] 2021-01-07 21:42
Since this isn't being expanded upon, and I can't replicate it, I'll close the issue.

Please message me or reopen an issue if you run into anything, or this persists

**Closed by VHRanger** 2021-01-07 21:42 UTC
