### ISSUE TITLE
some problem on the accuracy 

### ISSUE THREAD

**Issue by Tadelaide** [VHRanger/nodevectors#10] opened 2020-05-21 11:10 UTC
Hi, 

I an testing the code with blogcatelog datasets(download from the [OpenNe](https://github.com/thunlp/OpenNE) a repository of github) with your work.
Additionally, I have compare the multi-class result with the code in OpenNe. 
In my test, if I use 10 percent of data as training data, the result of your work is 
{'micro': 0.25313039723661485, 'macro': 0.12076017464146425};

In the same time, the code of OpenNe has achieve 
{'micro': 0.2903713298791019, 'macro': 0.1674684546080052};

I am very confused about this, because I find both of you use the gensim. I simplely think the problem occur in the node samples.  

I haven't do a deeper job right now but your code is really inspired me that it could used in a huge number of nodes. A good spark in Graph process.

Best regards,
Tade

**Comment by VHRanger** [comment] 2020-05-21 18:31
Hi,

What method from OpenNe are you using? My node2vec implementation generally gets similar link prediction and graph clustering results to the implementations from karateclub (another github graph embedding library).

If you are planning to embed huge graphs, I would be patient, there's a release in the works which lets you avoid using networkX altogether (reading an edgelist directly to a compact CSRGraph and embedding from it). 

I've had a few questions about embedding huge graphs, and generally networkX won't scale to huge graphs because you'll run out of RAM past a few hundred thousand nodes.

**Comment by VHRanger** [comment] 2020-06-03 17:54
Closing since I can't replicate the issue. See the link prediction notebook in the examples folder for reproduction code.

I'll reopen happily if we can replicate the performance issue.

**Closed by VHRanger** 2020-06-03 17:54 UTC
